//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail
    {
        public int id { get; set; }
        public string MailAdi { get; set; }
        public string MailSoyadi { get; set; }
        public string MailTelNo { get; set; }
        public string MailNot { get; set; }
    }
}
